### ISSUE TITLE
Can compress-pdf be compiled under Ubuntu?

### ISSUE THREAD

**Issue by curtis18** [maxim-puchkov/compress-pdf#7]
Hi there,

I would like to ask is the compression rate better than GhostScript? I tried to compile it under Ubuntu, the Swift prompted "error: no such module 'Quartz'", is it necessary to be compiled in MacOS? Thank you.

**Comment by maxim-puchkov** [comment]
Hello! 

This code depends on the Apple's Quartz framework. As far as I know, it is only available for macOS. You can find the documentation here: https://developer.apple.com/documentation/quartz. So I don't think this code will be able to run on Ubuntu. 

Regarding GhostScript, I'm not familiar with it, so I can't answer that question. But you can find some example documents in the README file and compress one of them with GhostScript, and then you will be able to compare the results yourself.

Maxim
