### ISSUE TITLE
error: no such module 'Quartz'

### ISSUE THREAD

**Issue by zhq5101** [maxim-puchkov/compress-pdf#9]
I tried to build compress-pdf on CentOS 7, but get an error: no such module 'Quartz'
![image](https://github.com/maxim-puchkov/compress-pdf/assets/32116688/607a6095-c0a5-4d74-8f2e-2acdded403cd)

![image](https://github.com/maxim-puchkov/compress-pdf/assets/32116688/ed37e56f-1f64-4806-8f1b-60757a6e5d31)

I'm new to swift. Any idea to install module 'Quartz'?

**Comment by maxim-puchkov** [comment]
Hey! Please take a look at my answer to a similar question: https://github.com/maxim-puchkov/compress-pdf/issues/8. In short, the Quartz framework is provided by Apple and is only available on macOS. It will not compile on any other system.

**Comment by zhq5101** [comment]
I see. Thank you for your response!
